CREATE TABLE members (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 provider VARCHAR(255) NOT NULL, provider_id VARCHAR(255) NOT NULL,
 email VARCHAR(255), nickname VARCHAR(30), birth_year INTEGER,
 profile_image_url VARCHAR(2048), profile_completed BOOLEAN NOT NULL DEFAULT FALSE,
 score BIGINT, UNIQUE(provider, provider_id), CHECK(birth_year IS NULL OR birth_year >= 1900)
);
CREATE TABLE hiking_records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 member_id BIGINT NOT NULL REFERENCES members(id), mountain_name VARCHAR(100) NOT NULL,
 title VARCHAR(100) NOT NULL, content VARCHAR(10000) NOT NULL,
 hiking_date DATE NOT NULL, is_public BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX hiking_records_member_visibility ON hiking_records(member_id,is_public,hiking_date);
