-- Existing hiking_records are journals. Preserve every legacy row without inventing an activity.
CREATE TABLE hiking_activities (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 member_id BIGINT NOT NULL REFERENCES members(id),
 mountain_id BIGINT NOT NULL REFERENCES mountains(id),
 course_id BIGINT REFERENCES courses(id),
 mountain_name VARCHAR(100) NOT NULL,
 started_at TIMESTAMP WITH TIME ZONE NOT NULL,
 ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
 distance_meters DOUBLE PRECISION NOT NULL CHECK (distance_meters >= 0),
 elapsed_ms BIGINT NOT NULL CHECK (elapsed_ms >= 0),
 completed BOOLEAN NOT NULL,
 client_request_id VARCHAR(36) NOT NULL,
 UNIQUE(member_id, client_request_id),
 CHECK (ended_at >= started_at)
);
CREATE INDEX hiking_activities_member_started ON hiking_activities(member_id, started_at);
ALTER TABLE hiking_records ADD COLUMN hiking_activity_id BIGINT REFERENCES hiking_activities(id);
ALTER TABLE hiking_records ADD CONSTRAINT journal_one_per_activity UNIQUE(hiking_activity_id);
